name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend  # Pfad zum Dockerfile des Frontends
        file: ./frontend/Dockerfile # Optional, falls Dockerfile nicht im Kontext liegt
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/battleproject-frontend:latest

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend   # Pfad zum Dockerfile des Backends
        file: ./backend/Dockerfile # Optional, falls Dockerfile nicht im Kontext liegt
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/battleproject-backend:latest
